import { useState } from "react";
import { jsPDF } from "jspdf";
import api from "./api/api";
import Navbar from "./components/Navbar";
import ReviewCard from "./components/ReviewCard";
import "./App.css";
import Loader from "./components/Loader";

function App() {

  const [code, setCode] = useState("");
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);

  const reviewCode = async () => {

    if (!code.trim()) {

      alert("Paste some code first");
      return;
    }

    try {

      setLoading(true);

      const response = await api.post(
        "/api/reviews",
        {
          code
        }
      );

      console.log(response.data);
      setResult(response.data);

    } catch (error) {

      console.error(error);

      alert(
        JSON.stringify(
          error.response?.data ||
          "Review failed"
        )
      );

    } finally {

      setLoading(false);
    }
  };

  const exportPdf = () => {

    if (!result) return;

    const doc = new jsPDF();

    doc.setFontSize(18);

    doc.text(
      "AI Code Review Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      "Generated By: Authenticated User",
      20,
      40
    );

    doc.text(
      `Language: ${result.language || "Unknown"}`,
      20,
      50
    );

    doc.text(
      `Score: ${result.score}/10`,
      20,
      60
    );

    let y = 80;

    doc.text(
      "Issues:",
      20,
      y
    );

    y += 10;

    result.issues?.forEach(issue => {

      if (y > 270) {

        doc.addPage();
        y = 20;
      }

      doc.text(
        `${issue.title} (${issue.severity})`,
        25,
        y
      );

      y += 10;
    });

    if (y > 220) {

      doc.addPage();
      y = 20;
    }

    y += 10;

    doc.text(
      "Improved Code:",
      20,
      y
    );

    y += 10;

    const improvedCodeLines =
      doc.splitTextToSize(
        result.improvedCode || "",
        170
      );

    doc.text(
      improvedCodeLines,
      20,
      y
    );

    doc.save(
      "review-report.pdf"
    );
  };

  const downloadImprovedCode = () => {

    if (!result?.improvedCode)
      return;

    const blob = new Blob(
      [result.improvedCode],
      {
        type: "text/plain"
      }
    );

    const url =
      window.URL.createObjectURL(
        blob
      );

    const link =
      document.createElement("a");

    link.href = url;

    link.download =
      "improved-code.txt";

    link.click();

    window.URL.revokeObjectURL(
      url
    );
  };

  const getSeverityColor = (severity) => {

    switch (severity) {

      case "CRITICAL":
        return "#ef4444";

      case "HIGH":
        return "#f97316";

      case "MEDIUM":
        return "#eab308";

      default:
        return "#22c55e";
    }
  };
  const formatIssueName = (issue) => {

    return issue
      .toLowerCase()
      .replaceAll("_", " ")
      .replace(
        /\b\w/g,
        char => char.toUpperCase()
      );
  };

  return (
    <>
      <Navbar />

      <div className="container">
        <div
          style={{
            marginBottom: "25px"
          }}
        >

          <h1
            style={{
              fontSize: "42px",
              marginBottom: "10px"
            }}
          >
            AI Multi-Language Code Review Assistant
          </h1>

          <p
            style={{
              color: "#94a3b8",
              fontSize: "18px"
            }}
          >
            Analyze, improve and optimize your code using AI.
          </p>

        </div>

        <textarea
          rows="20" style={{
            minHeight: "350px"
          }}
          placeholder="Paste code here..."
          value={code}
          onChange={(e) =>
            setCode(
              e.target.value
            )
          }
        />




        <button
          onClick={reviewCode}
          disabled={loading}
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            gap: "10px"
          }}
        >
          {
            loading ? (
              <>
                <Loader />
                Reviewing...
              </>
            ) : (
              "Review Code"
            )
          }
        </button>
        {
          result && (

            <div>

              <ReviewCard
                score={result.score}
              />

              <div
                style={{
                  marginTop: "20px"
                }}
              >
                <h2>
                  Language
                </h2>

                <div
                  style={{
                    display: "inline-block",
                    padding: "8px 16px",
                    background: "#2563eb",
                    borderRadius: "999px",
                    color: "white",
                    fontWeight: "bold"
                  }}
                >
                  {result.language}
                </div>
              </div>
              {
                result.personalizedRecommendation && (

                  <div
                    style={{
                      marginTop: "20px",
                      background:
                        "linear-gradient(135deg,#134e4a,#0f766e)",
                      padding: "20px",
                      borderRadius: "10px"
                    }}
                  >
                    <h2>
                      Personalized Recommendation
                    </h2>

                    <p>
                      {result.personalizedRecommendation}
                    </p>

                  </div>

                )
              }
              {
                result.recurringIssues &&
                result.recurringIssues.length > 0 && (

                  <div
                    style={{
                      marginTop: "20px",
                      background: "#1e293b",
                      padding: "20px",
                      borderRadius: "10px",
                      border: "1px solid #334155"
                    }}
                  >

                    <h2
                      style={{
                        marginBottom: "10px"
                      }}
                    >
                      🧠 Recurring Issues
                    </h2>

                    <p
                      style={{
                        color: "#94a3b8",
                        marginBottom: "20px"
                      }}
                    >
                      These issues have appeared repeatedly in your previous reviews.
                    </p>

                    {
                      result.recurringIssues.map(
                        (item, index) => (

                          <div
                            key={index}
                            style={{
                              padding: "10px",
                              marginTop: "10px",
                              background: "#0f172a",
                              borderRadius: "8px"
                            }}
                          >

                            <strong>
                              {
                                formatIssueName(
                                  item.issue
                                )
                              }
                            </strong>

                            {" "}
                            appeared

                            {" "}

                            <span
                              style={{
                                color: "#f59e0b",
                                fontWeight: "bold"
                              }}
                            >
                              {item.frequency}
                            </span>

                            {" "}

                            times
                            <div
                              style={{
                                width: "100%",
                                height: "10px",
                                background: "#334155",
                                borderRadius: "999px",
                                marginTop: "10px"
                              }}
                            >

                              <div
                                style={{
                                  width: `${Math.min(
                                    item.frequency * 20,
                                    100
                                  )}%`,
                                  height: "100%",
                                  background: "#3b82f6",
                                  borderRadius: "999px"
                                }}
                              />

                            </div>

                          </div>

                        )
                      )
                    }

                  </div>

                )
              }
              <div
                style={{
                  display: "grid",
                  gridTemplateColumns:
                    "repeat(auto-fit,minmax(200px,1fr))",
                  gap: "15px",
                  marginTop: "25px",
                  marginBottom: "20px"
                }}
              >

                <div
                  style={{
                    background:
                      "linear-gradient(135deg,#1e293b,#0f172a)",

                    padding: "25px",

                    borderRadius: "16px",

                    border:
                      "1px solid #334155",

                    boxShadow:
                      "0 8px 20px rgba(0,0,0,.25)"
                  }}
                >
                  <h3
                    style={{
                      color: "#94a3b8"
                    }}
                  >
                    Overall Score
                  </h3>
                  <h1>{result.score}/10</h1>
                </div>

                <div
                  style={{
                    background:
                      "linear-gradient(135deg,#1e293b,#0f172a)",

                    padding: "25px",

                    borderRadius: "16px",

                    border:
                      "1px solid #334155",

                    boxShadow:
                      "0 8px 20px rgba(0,0,0,.25)"
                  }}
                >
                  <h3
                    style={{
                      color: "#94a3b8"
                    }}
                  >
                    Issues Found
                  </h3>
                  <h1>{result.issues?.length || 0}</h1>
                </div>

                <div
                  style={{
                    background:
                      "linear-gradient(135deg,#1e293b,#0f172a)",

                    padding: "25px",

                    borderRadius: "16px",

                    border:
                      "1px solid #334155",

                    boxShadow:
                      "0 8px 20px rgba(0,0,0,.25)"
                  }}
                >
                  <h3
                    style={{
                      color: "#94a3b8"
                    }}
                  >
                    AI Suggestions
                  </h3>
                  <h1>{result.suggestions?.length || 0}</h1>
                </div>

              </div>
              <button
                onClick={exportPdf}
                style={{
                  marginTop: "15px",
                  marginBottom: "20px",
                  padding: "10px 20px"
                }}
              >
                Export PDF
              </button>
              <div
                style={{
                  background: "#1e293b",
                  padding: "20px",
                  borderRadius: "10px",
                  marginTop: "25px",
                  marginBottom: "20px"
                }}
              >



                {
                  // result.personalizedRecommendation && (

                  //   <div
                  //     style={{
                  //       marginTop: "15px",
                  //       color: "#22c55e",
                  //       fontWeight: "bold"
                  //     }}
                  //   >
                  //     {result.personalizedRecommendation}
                  //   </div>

                  // )
                }



              </div>
              <h2>
                Issues Found
              </h2>

              {
                result.issues?.map(
                  (
                    issue,
                    index
                  ) => (

                    <div
                      key={index}
                      style={{
                        background:
                          "#1e293b",
                        padding:
                          "15px",
                        borderRadius:
                          "10px",
                        marginTop:
                          "10px"
                      }}
                    >
                      <h3>
                        {issue.title}
                      </h3>

                      <p>
                        Severity:
                        {" "}
                        <strong
                          style={{
                            color:
                              getSeverityColor(
                                issue.severity
                              )
                          }}
                        >
                          {issue.severity}
                        </strong>
                      </p>

                      {
                        issue.line !== undefined &&
                        issue.line !== null && (

                          <p>
                            Line:
                            {" "}
                            {issue.line}
                          </p>

                        )
                      }

                      <p>
                        {issue.description}
                      </p>

                      <p>
                        <strong>
                          Fix:
                        </strong>
                        {" "}
                        {issue.fix}
                      </p>

                    </div>

                  )
                )
              }

              <h2
                style={{
                  marginTop: "30px"
                }}
              >
                AI Suggestions
              </h2>

              {
                result.suggestions?.map(
                  (
                    suggestion,
                    index
                  ) => (

                    <div
                      key={index}
                      style={{
                        background:
                          "#1e293b",
                        padding:
                          "12px",
                        marginTop:
                          "10px",
                        borderRadius:
                          "8px"
                      }}
                    >
                      💡 {suggestion}
                    </div>

                  )
                )
              }

              <h2
                style={{
                  marginTop: "30px"
                }}
              >
                Improved Code
              </h2>

              <div
                style={{
                  display: "flex",
                  gap: "10px",
                  marginBottom: "10px"
                }}
              >

                <button
                  onClick={() => {

                    navigator.clipboard.writeText(
                      result.improvedCode
                    );

                    alert(
                      "Code copied successfully"
                    );
                  }}
                  style={{
                    padding: "10px 20px",
                    border: "none",
                    borderRadius: "8px",
                    background: "#16a34a",
                    color: "white",
                    cursor: "pointer"
                  }}
                >
                  Copy Improved Code
                </button>

                <button
                  onClick={downloadImprovedCode}
                  style={{
                    padding: "10px 20px",
                    border: "none",
                    borderRadius: "8px",
                    background: "#2563eb",
                    color: "white",
                    cursor: "pointer"
                  }}
                >
                  Download Improved Code
                </button>

              </div>

              <pre
                style={{
                  background:
                    "#0f172a",
                  color:
                    "#e2e8f0",
                  padding:
                    "15px",
                  borderRadius:
                    "8px",
                  overflowX:
                    "auto",
                  whiteSpace:
                    "pre-wrap"
                }}
              >
                {result.improvedCode}
              </pre>

            </div>

          )
        }

      </div>
    </>
  );
}

export default App;